name: Build and Test JS/WASM

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          cache: yarn

      - name: Install Rust and Wasm-Pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Project
        run: yarn run build

      - name: Test Project
        run: yarn run test

      - name: Package Built Files
        run: zip -r artifact.zip dist/
        # If you prefer zip, use the following line instead:
        # run: zip -r artifact.zip dist/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: built-js-module
          path: artifact.zip
          # If you used zip, change the path to artifact.zip:
          # path: artifact.zip
